### ISSUE TITLE
ML Number 

### ISSUE THREAD

**Issue by Ashleighmaida** [OvilleTown/Oville.MarraigeLicensesIssues#29]
When submitting a new marriage license application, it asks for a Marriage License number. They applicants will not have this number, maybe we could change it to ask them for both parties last names (as i've entered it in my test submissions). That is typically how we enter them now until they are printed and assigned a license number.

**Comment by OvilleTown** [comment]
Can you screenshot where it is showing the license number please?

**Comment by Ashleighmaida** [comment]
Hey Dan,

Looking back at your email- I entered them into the CRM portion ‘- this may have been the wrong spot. I don’t see my entries anymore, they may have been deleted?

I see your ‘link for the testing solution’, but it does give me an error prompt.

Thanks,
Ash
