### ISSUE TITLE
Blocking Timeslot Issue 

### ISSUE THREAD

**Issue by gspratt** [OvilleTown/Oville.MarraigeLicensesIssues#49]
**Describe the bug**
Tried to block a time through the admin portal for 9:00a.m to 9:30a.m. Tried blocking that timeframe and outside of it as it was not working. Tried 8:59a.m-9:30a.m, 8:30a.m-9:30a.m. Only seemed to block when I did 12:00a.m-9:30a.m

**To Reproduce**
1. Go to 'https://marriageadmin.orangeville.ca/'
2. Click on 'Create New'
4. Create block time from 9:00a.m-9:30a.m and SAVE
5. Click on 'Sync CRM Data to Local Site'
6. Go to your test application booking - mine was 'https://marriagelicencetest.orangeville.ca/home/status/2022-APOBIDV3FUSQ7AGBZXBQCQ'
7. Click on calendar and search for Oct 12th 9:00a.m - Still shows up

**Expected behavior**
This time should not be visible and should be blocked out from the publics view.

**Screenshots**
![image](https://user-images.githubusercontent.com/111531263/186500564-c1a32ea7-c979-4791-ad94-1e5728263e62.png)
![image](https://user-images.githubusercontent.com/111531263/186500899-b2be5f59-a52c-4af2-b04c-9d9f64c85128.png)

**Browser (please complete the following information):**
 - Browser CHROME

**Additional context**
It seems that if you block starting at 12:00A.M and put any end time lets say 12:00p.m. It will block that window of time. But for small timeslots of 30 minutes I cant block these.

**Comment by gspratt** [comment]
Only time that this time blocking works it seems is when the time starts at 12:00a.m and ends whenever specified. Just tried blocking 12:00p.m to 4:00p.m and it doesn't work, but when you do 12:00a,m to 4:00p.m it works....

**Comment by OvilleTown** [comment]
The dates and time issue should be fixed.  You also don't need to hit Sync CRM data to local site.  This is only required for changes to things such as countries.
