### ISSUE TITLE
Calender

### ISSUE THREAD

**Issue by alwaysdi** [OvilleTown/Oville.MarraigeLicensesIssues#50]
**Describe the bug**
calendar to choose appointment month the top is cut off on laptop screen cannot see month name if I move page over to monitor it moves calendar to a different position and I can see it.

**To Reproduce**
1. Go to pay/schedule appointment
2. Click on calendar pic
3. See error

**Expected behavior**
expected to see name of month and full monthly calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/71290905/186764527-0f5812e6-0442-4b43-9823-743e7e30cb5a.png)

**Browser (please complete the following information):**

**Additional context**

**Comment by OvilleTown** [comment]
This is actually caused by eSolutions the way the built the website.  It has been that way since day one, but I can't do anything about it, it is the styling from eSolutions.  If you scroll down more on the page it will switch to open on the bottom.
